# Generated by Django 4.0.4 on 2022-10-13 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_avatar_user_image_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
