# Generated by Django 4.0.4 on 2022-10-29 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_orderdetail_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('_deleted', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_creator', to=settings.AUTH_USER_MODEL)),
                ('_updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_updater', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='api.product')),
            ],
        ),
    ]
