# Generated by Django 4.0.4 on 2022-11-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_address_order_note_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVE', 'APPROVE')], default='PENDING', max_length=7),
        ),
    ]
