# Generated by Django 4.0.4 on 2022-12-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_favoriteproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=1024)),
                ('code', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
    ]
